project:
  type: website
  output-dir: docs

website:
  title: "ðŸ˜‚ ðŸ¤£ ðŸ˜‚"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01_dummy.ipynb
        text: Dummy
      - href: 02_decision-tree.ipynb
        text: DecisionTree

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



